name: Notify Telegram on Commit & Release

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on Commit
        if: github.event_name == 'push'
        run: |
          curl -s -X POST https://api.telegram.org/bot7457097413:AAF0eKMO6rJUmp7OIbVxqd2Mt0Em84TqsG4/sendMessage \
          -d chat_id=-1002394824391 \
          -d text="ğŸš€ *Neuer Commit in* [${{ github.repository }}](https://github.com/${{ github.repository }})%0AğŸ‘¤ *Autor:* ${{ github.actor }}%0AğŸ“œ *Nachricht:* `${{ github.event.head_commit.message }}`%0AğŸ”— [Commit ansehen](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" \
          -d parse_mode=Markdown

      - name: Send Telegram message on Release
        if: github.event_name == 'release'
        run: |
          curl -s -X POST https://api.telegram.org/bot7457097413:AAF0eKMO6rJUmp7OIbVxqd2Mt0Em84TqsG4/sendMessage \
          -d chat_id=-1002394824391 \
          -d text="ğŸ‰ *Neues Release verÃ¶ffentlicht!*%0AğŸ“¦ *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})%0AğŸ· *Tag:* `${{ github.event.release.tag_name }}`%0AğŸ“ *Beschreibung:* `${{ github.event.release.body }}`%0AğŸ”— [Release ansehen](${{ github.event.release.html_url }})" \
          -d parse_mode=Markdown
